<!DOCTYPE html>

<html lang="en" class="devsite wf-opensans-n4-active wf-active">
<!-- Mirrored from www.sketchup.com/intl/en/developer/docs/ourdoc/entities by HTTrack Website Copier/3.x [XR&CO'2014], Mon, 11 Apr 2016 13:59:36 GMT -->
<head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><script type="text/javascript">(window.NREUM||(NREUM={})).loader_config={xpid:"VwQOVFBRGwIIXVVVDgU="};window.NREUM||(NREUM={}),__nr_require=function(t,e,n){function r(n){if(!e[n]){var o=e[n]={exports:{}};t[n][0].call(o.exports,function(e){var o=t[n][1][e];return r(o||e)},o,o.exports)}return e[n].exports}if("function"==typeof __nr_require)return __nr_require;for(var o=0;o<n.length;o++)r(n[o]);return r}({1:[function(t,e,n){function r(t){try{s.console&&console.log(t)}catch(e){}}var o,i=t("ee"),a=t(11),s={};try{o=localStorage.getItem("__nr_flags").split(","),console&&"function"==typeof console.log&&(s.console=!0,-1!==o.indexOf("dev")&&(s.dev=!0),-1!==o.indexOf("nr_dev")&&(s.nrDev=!0))}catch(c){}s.nrDev&&i.on("internal-error",function(t){r(t.stack)}),s.dev&&i.on("fn-err",function(t,e,n){r(n.stack)}),s.dev&&(r("NR AGENT IN DEVELOPMENT MODE"),r("flags: "+a(s,function(t,e){return t}).join(", ")))},{}],2:[function(t,e,n){function r(t,e,n,r,o){try{d?d-=1:i("err",[o||new UncaughtException(t,e,n)])}catch(s){try{i("ierr",[s,(new Date).getTime(),!0])}catch(c){}}return"function"==typeof f?f.apply(this,a(arguments)):!1}function UncaughtException(t,e,n){this.message=t||"Uncaught error with no additional information",this.sourceURL=e,this.line=n}function o(t){i("err",[t,(new Date).getTime()])}var i=t("handle"),a=t(12),s=t("ee"),c=t("loader"),f=window.onerror,u=!1,d=0;c.features.err=!0,t(1),window.onerror=r;try{throw new Error}catch(l){"stack"in l&&(t(5),t(4),"addEventListener"in window&&t(3),c.xhrWrappable&&t(6),u=!0)}s.on("fn-start",function(t,e,n){u&&(d+=1)}),s.on("fn-err",function(t,e,n){u&&(this.thrown=!0,o(n))}),s.on("fn-end",function(){u&&!this.thrown&&d>0&&(d-=1)}),s.on("internal-error",function(t){i("ierr",[t,(new Date).getTime(),!0])})},{}],3:[function(t,e,n){function r(t){for(var e=t;e&&!e.hasOwnProperty(u);)e=Object.getPrototypeOf(e);e&&o(e)}function o(t){s.inPlace(t,[u,d],"-",i)}function i(t,e){return t[1]}var a=t("ee").get("events"),s=t(13)(a),c=t("gos"),f=XMLHttpRequest,u="addEventListener",d="removeEventListener";e.exports=a,"getPrototypeOf"in Object?(r(document),r(window),r(f.prototype)):f.prototype.hasOwnProperty(u)&&(o(window),o(f.prototype)),a.on(u+"-start",function(t,e){if(t[1]){var n=t[1];if("function"==typeof n){var r=c(n,"nr@wrapped",function(){return s(n,"fn-",null,n.name||"anonymous")});this.wrapped=t[1]=r}else"function"==typeof n.handleEvent&&s.inPlace(n,["handleEvent"],"fn-")}}),a.on(d+"-start",function(t){var e=this.wrapped;e&&(t[1]=e)})},{}],4:[function(t,e,n){var r=t("ee").get("raf"),o=t(13)(r);e.exports=r,o.inPlace(window,["requestAnimationFrame","mozRequestAnimationFrame","webkitRequestAnimationFrame","msRequestAnimationFrame"],"raf-"),r.on("raf-start",function(t){t[0]=o(t[0],"fn-")})},{}],5:[function(t,e,n){function r(t,e,n){t[0]=a(t[0],"fn-",null,n)}function o(t,e,n){this.method=n,this.timerDuration="number"==typeof t[1]?t[1]:0,t[0]=a(t[0],"fn-",this,n)}var i=t("ee").get("timer"),a=t(13)(i);e.exports=i,a.inPlace(window,["setTimeout","setImmediate"],"setTimer-"),a.inPlace(window,["setInterval"],"setInterval-"),a.inPlace(window,["clearTimeout","clearImmediate"],"clearTimeout-"),i.on("setInterval-start",r),i.on("setTimer-start",o)},{}],6:[function(t,e,n){function r(t,e){d.inPlace(e,["onreadystatechange"],"fn-",s)}function o(){var t=this,e=u.context(t);t.readyState>3&&!e.resolved&&(e.resolved=!0,u.emit("xhr-resolved",[],t)),d.inPlace(t,v,"fn-",s)}function i(t){y.push(t),h&&(g=-g,x.data=g)}function a(){for(var t=0;t<y.length;t++)r([],y[t]);y.length&&(y=[])}function s(t,e){return e}function c(t,e){for(var n in t)e[n]=t[n];return e}t(3);var f=t("ee"),u=f.get("xhr"),d=t(13)(u),l=NREUM.o,p=l.XHR,h=l.MO,m="readystatechange",v=["onload","onerror","onabort","onloadstart","onloadend","onprogress","ontimeout"],y=[];e.exports=u;var w=window.XMLHttpRequest=function(t){var e=new p(t);try{u.emit("new-xhr",[e],e),e.addEventListener(m,o,!1)}catch(n){try{u.emit("internal-error",[n])}catch(r){}}return e};if(c(p,w),w.prototype=p.prototype,d.inPlace(w.prototype,["open","send"],"-xhr-",s),u.on("send-xhr-start",function(t,e){r(t,e),i(e)}),u.on("open-xhr-start",r),h){var g=1,x=document.createTextNode(g);new h(a).observe(x,{characterData:!0})}else f.on("fn-end",function(t){t[0]&&t[0].type===m||a()})},{}],7:[function(t,e,n){function r(t){var e=this.params,n=this.metrics;if(!this.ended){this.ended=!0;for(var r=0;l>r;r++)t.removeEventListener(d[r],this.listener,!1);if(!e.aborted){if(n.duration=(new Date).getTime()-this.startTime,4===t.readyState){e.status=t.status;var i=o(t,this.lastSize);if(i&&(n.rxSize=i),this.sameOrigin){var a=t.getResponseHeader("X-NewRelic-App-Data");a&&(e.cat=a.split(", ").pop())}}else e.status=0;n.cbTime=this.cbTime,u.emit("xhr-done",[t],t),c("xhr",[e,n,this.startTime])}}}function o(t,e){var n=t.responseType;if("json"===n&&null!==e)return e;var r="arraybuffer"===n||"blob"===n||"json"===n?t.response:t.responseText;return i(r)}function i(t){if("string"==typeof t&&t.length)return t.length;if("object"==typeof t){if("undefined"!=typeof ArrayBuffer&&t instanceof ArrayBuffer&&t.byteLength)return t.byteLength;if("undefined"!=typeof Blob&&t instanceof Blob&&t.size)return t.size;if(!("undefined"!=typeof FormData&&t instanceof FormData))try{return JSON.stringify(t).length}catch(e){return}}}function a(t,e){var n=f(e),r=t.params;r.host=n.hostname+":"+n.port,r.pathname=n.pathname,t.sameOrigin=n.sameOrigin}var s=t("loader");if(s.xhrWrappable){var c=t("handle"),f=t(8),u=t("ee"),d=["load","error","abort","timeout"],l=d.length,p=t("id"),h=t(10),m=window.XMLHttpRequest;s.features.xhr=!0,t(6),u.on("new-xhr",function(t){var e=this;e.totalCbs=0,e.called=0,e.cbTime=0,e.end=r,e.ended=!1,e.xhrGuids={},e.lastSize=null,h&&(h>34||10>h)||window.opera||t.addEventListener("progress",function(t){e.lastSize=t.loaded},!1)}),u.on("open-xhr-start",function(t){this.params={method:t[0]},a(this,t[1]),this.metrics={}}),u.on("open-xhr-end",function(t,e){"loader_config"in NREUM&&"xpid"in NREUM.loader_config&&this.sameOrigin&&e.setRequestHeader("X-NewRelic-ID",NREUM.loader_config.xpid)}),u.on("send-xhr-start",function(t,e){var n=this.metrics,r=t[0],o=this;if(n&&r){var a=i(r);a&&(n.txSize=a)}this.startTime=(new Date).getTime(),this.listener=function(t){try{"abort"===t.type&&(o.params.aborted=!0),("load"!==t.type||o.called===o.totalCbs&&(o.onloadCalled||"function"!=typeof e.onload))&&o.end(e)}catch(n){try{u.emit("internal-error",[n])}catch(r){}}};for(var s=0;l>s;s++)e.addEventListener(d[s],this.listener,!1)}),u.on("xhr-cb-time",function(t,e,n){this.cbTime+=t,e?this.onloadCalled=!0:this.called+=1,this.called!==this.totalCbs||!this.onloadCalled&&"function"==typeof n.onload||this.end(n)}),u.on("xhr-load-added",function(t,e){var n=""+p(t)+!!e;this.xhrGuids&&!this.xhrGuids[n]&&(this.xhrGuids[n]=!0,this.totalCbs+=1)}),u.on("xhr-load-removed",function(t,e){var n=""+p(t)+!!e;this.xhrGuids&&this.xhrGuids[n]&&(delete this.xhrGuids[n],this.totalCbs-=1)}),u.on("addEventListener-end",function(t,e){e instanceof m&&"load"===t[0]&&u.emit("xhr-load-added",[t[1],t[2]],e)}),u.on("removeEventListener-end",function(t,e){e instanceof m&&"load"===t[0]&&u.emit("xhr-load-removed",[t[1],t[2]],e)}),u.on("fn-start",function(t,e,n){e instanceof m&&("onload"===n&&(this.onload=!0),("load"===(t[0]&&t[0].type)||this.onload)&&(this.xhrCbStart=(new Date).getTime()))}),u.on("fn-end",function(t,e){this.xhrCbStart&&u.emit("xhr-cb-time",[(new Date).getTime()-this.xhrCbStart,this.onload,e],e)})}},{}],8:[function(t,e,n){e.exports=function(t){var e=document.createElement("a"),n=window.location,r={};e.href=t,r.port=e.port;var o=e.href.split("://");!r.port&&o[1]&&(r.port=o[1].split("http://www.sketchup.com/")[0].split("@").pop().split(":")[1]),r.port&&"0"!==r.port||(r.port="https"===o[0]?"443":"80"),r.hostname=e.hostname||n.hostname,r.pathname=e.pathname,r.protocol=o[0],"/"!==r.pathname.charAt(0)&&(r.pathname="/"+r.pathname);var i=!e.protocol||":"===e.protocol||e.protocol===n.protocol,a=e.hostname===document.domain&&e.port===n.port;return r.sameOrigin=i&&(!e.hostname||a),r}},{}],9:[function(t,e,n){function r(t,e){return function(){o(t,[(new Date).getTime()].concat(a(arguments)),null,e)}}var o=t("handle"),i=t(11),a=t(12);"undefined"==typeof window.newrelic&&(newrelic=NREUM);var s=["setPageViewName","addPageAction","setCustomAttribute","finished","addToTrace","inlineHit"],c=["addPageAction"],f="api-";i(s,function(t,e){newrelic[e]=r(f+e,"api")}),i(c,function(t,e){newrelic[e]=r(f+e)}),e.exports=newrelic,newrelic.noticeError=function(t){"string"==typeof t&&(t=new Error(t)),o("err",[t,(new Date).getTime()])}},{}],10:[function(t,e,n){var r=0,o=navigator.userAgent.match(/Firefox[\/\s](\d+\.\d+)/);o&&(r=+o[1]),e.exports=r},{}],11:[function(t,e,n){function r(t,e){var n=[],r="",i=0;for(r in t)o.call(t,r)&&(n[i]=e(r,t[r]),i+=1);return n}var o=Object.prototype.hasOwnProperty;e.exports=r},{}],12:[function(t,e,n){function r(t,e,n){e||(e=0),"undefined"==typeof n&&(n=t?t.length:0);for(var r=-1,o=n-e||0,i=Array(0>o?0:o);++r<o;)i[r]=t[e+r];return i}e.exports=r},{}],13:[function(t,e,n){function r(t){return!(t&&"function"==typeof t&&t.apply&&!t[a])}var o=t("ee"),i=t(12),a="nr@original",s=Object.prototype.hasOwnProperty,c=!1;e.exports=function(t){function e(t,e,n,o){function nrWrapper(){var r,a,s,c;try{a=this,r=i(arguments),s="function"==typeof n?n(r,a):n||{}}catch(u){d([u,"",[r,a,o],s])}f(e+"start",[r,a,o],s);try{return c=t.apply(a,r)}catch(l){throw f(e+"err",[r,a,l],s),l}finally{f(e+"end",[r,a,c],s)}}return r(t)?t:(e||(e=""),nrWrapper[a]=t,u(t,nrWrapper),nrWrapper)}function n(t,n,o,i){o||(o="");var a,s,c,f="-"===o.charAt(0);for(c=0;c<n.length;c++)s=n[c],a=t[s],r(a)||(t[s]=e(a,f?s+o:o,i,s))}function f(e,n,r){if(!c){c=!0;try{t.emit(e,n,r)}catch(o){d([o,e,n,r])}c=!1}}function u(t,e){if(Object.defineProperty&&Object.keys)try{var n=Object.keys(t);return n.forEach(function(n){Object.defineProperty(e,n,{get:function(){return t[n]},set:function(e){return t[n]=e,e}})}),e}catch(r){d([r])}for(var o in t)s.call(t,o)&&(e[o]=t[o]);return e}function d(e){try{t.emit("internal-error",e)}catch(n){}}return t||(t=o),e.inPlace=n,e.flag=a,e}},{}],ee:[function(t,e,n){function r(){}function o(t){function e(t){return t&&t instanceof r?t:t?s(t,a,i):i()}function n(n,r,o){t&&t(n,r,o);for(var i=e(o),a=l(n),s=a.length,c=0;s>c;c++)a[c].apply(i,r);var u=f[v[n]];return u&&u.push([y,n,r,i]),i}function d(t,e){m[t]=l(t).concat(e)}function l(t){return m[t]||[]}function p(t){return u[t]=u[t]||o(n)}function h(t,e){c(t,function(t,n){e=e||"feature",v[n]=e,e in f||(f[e]=[])})}var m={},v={},y={on:d,emit:n,get:p,listeners:l,context:e,buffer:h};return y}function i(){return new r}var a="nr@context",s=t("gos"),c=t(11),f={},u={},d=e.exports=o();d.backlog=f},{}],gos:[function(t,e,n){function r(t,e,n){if(o.call(t,e))return t[e];var r=n();if(Object.defineProperty&&Object.keys)try{return Object.defineProperty(t,e,{value:r,writable:!0,enumerable:!1}),r}catch(i){}return t[e]=r,r}var o=Object.prototype.hasOwnProperty;e.exports=r},{}],handle:[function(t,e,n){function r(t,e,n,r){o.buffer([t],r),o.emit(t,e,n)}var o=t("ee").get("handle");e.exports=r,r.ee=o},{}],id:[function(t,e,n){function r(t){var e=typeof t;return!t||"object"!==e&&"function"!==e?-1:t===window?0:a(t,i,function(){return o++})}var o=1,i="nr@id",a=t("gos");e.exports=r},{}],loader:[function(t,e,n){function r(){if(!m++){var t=h.info=NREUM.info,e=u.getElementsByTagName("script")[0];if(t&&t.licenseKey&&t.applicationID&&e){c(l,function(e,n){t[e]||(t[e]=n)});var n="https"===d.split(":")[0]||t.sslForHttp;h.proto=n?"https://":"http://",s("mark",["onload",a()],null,"api");var r=u.createElement("script");r.src=h.proto+t.agent,e.parentNode.insertBefore(r,e)}}}function o(){"complete"===u.readyState&&i()}function i(){s("mark",["domContent",a()],null,"api")}function a(){return(new Date).getTime()}var s=t("handle"),c=t(11),f=window,u=f.document;NREUM.o={ST:setTimeout,CT:clearTimeout,XHR:f.XMLHttpRequest,REQ:f.Request,EV:f.Event,PR:f.Promise,MO:f.MutationObserver},t(9);var d=""+location,l={beacon:"bam.nr-data.net",errorBeacon:"bam.nr-data.net",agent:"js-agent.newrelic.com/nr-918.min.js"},p=window.XMLHttpRequest&&XMLHttpRequest.prototype&&XMLHttpRequest.prototype.addEventListener&&!/CriOS/.test(navigator.userAgent),h=e.exports={offset:a(),origin:d,features:{},xhrWrappable:p};u.addEventListener?(u.addEventListener("DOMContentLoaded",i,!1),f.addEventListener("load",r,!1)):(u.attachEvent("onreadystatechange",o),f.attachEvent("onload",r)),s("mark",["firstbyte",a()],null,"api");var m=0},{}]},{},["loader",2,7]);</script>
    <meta charset="utf-8">
    <script src="../../assets/script_head.js"></script>
    <link rel="stylesheet" type="text/css" href="../../assets/screen.css">
    
    <link rel="shortcut icon" href="http://www.sketchup.com/sites/all/themes/sketchup/images/favicon.ico">
    
    
    <script src="../../assets/jquery.min.js"></script>
    <script id="jqueryui" src="../../assets/jquery-ui.min.js"></script>
    <script src="../../assets/jsapi.js"></script>
    <script>
      google.load('visualization', '1', {packages: ['table']});
    </script><script src="../../assets/saved_resource" type="text/javascript"></script><script src="../../assets/format%2ben%2cdefault%2ctable.I.js" type="text/javascript"></script><style>.a-b-c{position:relative;display:-moz-inline-box;display:inline-block}* html .a-b-c,*:first-child+html .a-b-c{display:inline}.a-d-e{margin:2px;border:0;padding:0;font-family:Arial,sans-serif;color:#000;background:#ddd url(../../../../../../ssl.gstatic.com/editor/button-bg.png) repeat-x top left;text-decoration:none;list-style:none;vertical-align:middle;cursor:default;outline:none}.a-d-e-f-g,.a-d-e-h-g{border-style:solid;border-color:#aaa;vertical-align:top}.a-d-e-f-g{margin:0;border-width:1px 0;padding:0}.a-d-e-h-g{-moz-box-orient:vertical;margin:0 -1px;border-width:0 1px;padding:3px 4px;white-space:nowrap}* html .a-d-e-h-g{left:-1px}* html .a-d-e-i .a-d-e-f-g{left:-1px}* html .a-d-e-i .a-d-e-h-g{right:auto}*:first-child+html .a-d-e-h-g{left:-1px}*:first-child+html .a-d-e-i .a-d-e-h-g{left:1px}::root .a-d-e,::root .a-d-e-f-g{line-height:0}::root .a-d-e-h-g{line-height:normal}.a-d-e-j{background-image:none!important;opacity:.3;-moz-opacity:.3;filter:alpha(opacity=30)}.a-d-e-j .a-d-e-f-g,.a-d-e-j .a-d-e-h-g{color:#333!important;border-color:#999!important}* html .a-d-e-j,*:first-child+html .a-d-e-j{margin:2px 1px!important;padding:0 1px!important}.a-d-e-k .a-d-e-f-g,.a-d-e-k .a-d-e-h-g{border-color:#9cf #69e #69e #7af!important}.a-d-e-l,.a-d-e-m{background-color:#bbb;background-position:bottom left}.a-d-e-n .a-d-e-f-g,.a-d-e-n .a-d-e-h-g{border-color:orange}.a-d-e-o-p,.a-d-e-o-p .a-d-e-f-g,.a-d-e-o-p .a-d-e-h-g{margin-right:0}.a-d-e-o-q,.a-d-e-o-q .a-d-e-f-g{margin-left:0}.a-d-e-o-q .a-d-e-h-g{margin-left:0;border-left:1px solid #fff}.a-d-e-o-q.a-d-e-m .a-d-e-h-g{border-left:1px solid #ddd}* html .a-d-e-o-q .a-d-e-h-g,*:first-child+html .a-d-e-o-q .a-d-e-h-g{left:0}.a-r-e{position:relative;margin:2px;border:1px solid #000;padding:2px 6px;font:normal 13px "Trebuchet MS",Tahoma,Arial,sans-serif;color:#fff;background-color:#8c2425;cursor:pointer;outline:none}.a-r-e-j{border-color:#888;color:#888;background-color:#ccc;cursor:default}.a-r-e-k{border-color:#8c2425;color:#8c2425;background-color:#eaa4a5}.a-r-e-l,.a-r-e-s,.a-r-e-m{border-color:#5b4169;color:#5b4169;background-color:#d1a8ea}.a-r-e-n{border-color:#5b4169}.a-r-e-o-p{margin-right:0}.a-r-e-o-q{margin-left:0;border-left:none}.a-e{color:#036;border-color:#036;background-color:#69c}.a-e-j{border-color:#333;color:#333;background-color:#999}.a-e-k{color:#369;border-color:#369;background-color:#9cf}.a-e-l{color:#69c;border-color:#69c}</style><link href="../../assets/table.css" rel="stylesheet" type="text/css">
    <script type="text/javascript" src="../../assets/api.js"></script>
    <!--[if lt IE 9]>
    <script src="/_static/js/html5shim/html5.js"></script>
    <![endif]-->
    <!--[if IE]>
      <style>
      #sketchup-toc {
        position: relative;
        left: -40px;
        width: 200px;
      }

      body {
        overflow: visible;
      }
      </style>
    <![endif]-->
    
    <script>
      google.load('search', '1', {language : 'en'});
    </script><script src="../../assets/saved_resource(1)" type="text/javascript"></script><script src="../../assets/default%2ben.I.js" type="text/javascript"></script>
    

    
  <script type="text/javascript">
    var contentTimer = new window.jstiming.Timer();

    var ___gcfg = ___gcfg || {};
    ___gcfg.lang = 'en';
  </script>
  <script src="../../assets/jquery-ui.min.js"></script>
  
  <title>SketchUp Ruby API</title>
  
  
  
    
    
    <link href="../../css/local_extensions.css" rel="stylesheet" type="text/css"><link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans">
  


    
    

  </head>
  <body class="two-column docs">
    
	<div id="header">
		<h1>
		  <a href="http://www.sketchup.com/"><img alt="Trimble SketchUp" src=
		  "../../../../../images/SU_Logo.png" width="190" height="40"></a>
		</h1>
	</div>
    
    

    <div id="gc-wrapper" itemscope="" itemtype="http://schema.org/Article">
      
      
      

      

      
      
      

      
      
      

      
      

      
      <div id="gc-main">
        
      
      
      <div id="gc-sidebar">
        

  


<a class="navitem-top" href="http://www.sketchup.com/">Home</a>
<br/><a href="../../index.html" class="navitem-top" style="color:#444;font-weight:bold">Developer Docs</a>

  <nav class="gc-toc"><ul id="sketchup-toc"><li class=""><a class="tlw-control tlw-collapsed">&nbsp;</a><span class="tlw-title tlw-control-title" data-title="Introduction">Introduction</span><ul >
<li class=""><a class="tlw-control tlw-collapsed">&nbsp;</a><span class="tlw-title tlw-control-title" data-title="Getting Started">Getting Started</span><ul >
<li class=""><a href="../faq.html" data-title="FAQ"><span>FAQ</span></a></li>
<li class=""><a href="../new_to_ruby.html" data-title="New to Ruby?"><span>New to Ruby?</span></a></li>
<li class=""><a href="../tutorial_console.html" data-title="The Ruby Console"><span>The Ruby Console</span></a></li>
<li class=""><a href="../tutorial_helloworld.html" data-title="Hello, World"><span>Hello, World</span></a></li>
<li class=""><a href="../examples.html" data-title="Example Files"><span>Example Files</span></a></li>
</ul></li>
<li class=""><a class="tlw-control tlw-collapsed">&nbsp;</a><span class="tlw-title tlw-control-title" data-title="Tutorials">Tutorials</span><ul ><li class=""><a href="../tutorial_geometry.html" data-title="Creating Geometry"><span>Creating Geometry</span></a></li>
<li class=""><a href="../tutorial_camera.html" data-title="Moving the Camera"><span>Moving the Camera</span></a></li>
<li class=""><a href="../loading.html" data-title="Loading Ruby Scripts"><span>Loading Ruby Scripts</span></a></li>
<li class=""><a href="../tutorial_attrreporting.html" data-title="Attribute Reporting"><span>Attribute Reporting</span></a></li>
<li class=""><a href="../tutorial_distributing.html" data-title="Distributing your Extension"><span>Distributing your Extension</span></a></li>
<li class=""><a href="../tutorial_licensing.html" data-title="Extension Licensing"><span>Extension Licensing</span></a></li>
</ul></li>
</ul></li>
<li class=""><a class="tlw-control tlw-collapsed">&nbsp;</a>
  
  <span class="tlw-title tlw-control-title" data-title="Quick Reference">Quick Reference</span><ul id="quick-reference-nav"><li class=""><a href="../classes.html" data-title="Class Index"><span>Class Index</span></a></li>
<li class=""><a href="../methods.html" data-title="Method Index"><span>Method Index</span></a></li>
<li class=""><a href="../utilities.html" data-title="Utilities"><span>Utilities</span></a></li>
</ul></li>

  
 <li class=""><a class="tlw-control tlw-expanded">&nbsp;</a><span class="tlw-title tlw-control-title" data-title="Object Reference">Object Reference</span><ul style=""><li class=""><a class="tlw-control tlw-collapsed">&nbsp;</a><span class="tlw-title tlw-control-title" data-title="App Level Classes">App Level Classes</span><ul ><li class=""><a href="sketchup.html" data-title="Sketchup"><span>Sketchup</span></a></li>
<li class=""><a href="model.html" data-title="Model"><span>Model</span></a></li>
<li class=""><a href="attributedictionary.html" data-title="Attribute Dictionary"><span>Attribute Dictionary</span></a></li>
<li class=""><a href="animation.html" data-title="Animation"><span>Animation</span></a></li>
<li class=""><a href="camera.html" data-title="Camera"><span>Camera</span></a></li>
<li class=""><a href="color.html" data-title="Color"><span>Color</span></a></li>
<li class=""><a href="extensionlicense.html" data-title="ExtensionLicense"><span>ExtensionLicense</span></a></li>
<li class=""><a href="sketchupextension.html" data-title="Extension"><span>Extension</span></a></li>
<li class=""><a href="importer.html" data-title="Importer"><span>Importer</span></a></li>
<li class=""><a href="languagehandler.html" data-title="LanguageHandler"><span>LanguageHandler</span></a></li>
<li class=""><a href="licensing.html" data-title="Licensing"><span>Licensing</span></a></li>
<li class=""><a href="optionsmanager.html" data-title="OptionsManager"><span>OptionsManager</span></a></li>
<li class=""><a href="optionsprovider.html" data-title="OptionsProvider"><span>OptionsProvider</span></a></li>
<li class=""><a href="set.html" data-title="Set"><span>Set</span></a></li>
<li class=""><a href="texturewriter.html" data-title="TextureWriter"><span>TextureWriter</span></a></li>
<li class=""><a href="view.html" data-title="View"><span>View</span></a></li>
<li class=""><a href="uvhelper.html" data-title="UVHelper"><span>UVHelper</span></a></li>
</ul></li>
<li class=""><a class="tlw-control tlw-collapsed">&nbsp;</a><span class="tlw-title tlw-control-title" data-title="Entity Classes">Entity Classes</span><ul >
<li class=""><a href="entity.html" data-title="Entity"><span>Entity</span></a></li>
<li class=""><a href="drawingelement.html" data-title="Drawingelement"><span>Drawingelement</span></a></li>
<li class=""><a href="arccurve.html" data-title="ArcCurve"><span>ArcCurve</span></a></li>
<li class=""><a href="axes.html" data-title="Axes"><span>Axes</span></a></li>
<li class=""><a href="behavior.html" data-title="Behavior"><span>Behavior</span></a></li>
<li class=""><a href="classificationschema.html" data-title="ClassificationSchema"><span>ClassificationSchema</span></a></li>
<li class=""><a href="componentdefinition.html" data-title="ComponentDefinition"><span>ComponentDefinition</span></a></li>
<li class=""><a href="componentinstance.html" data-title="ComponentInstance"><span>ComponentInstance</span></a></li>
<li class=""><a href="constructionline.html" data-title="ConstructionLine"><span>ConstructionLine</span></a></li>
<li class=""><a href="constructionpoint.html" data-title="ConstructionPoint"><span>ConstructionPoint</span></a></li>
<li class=""><a href="curve.html" data-title="Curve"><span>Curve</span></a></li>
<li class=""><a href="dimension.html" data-title="Dimension"><span>Dimension</span></a></li>
<li class=""><a href="dimensionlinear.html" data-title="DimensionLinear"><span>DimensionLinear</span></a></li>
<li class=""><a href="dimensionradial.html" data-title="DimensionRadial"><span>DimensionRadial</span></a></li>
<li class=""><a href="edge.html" data-title="Edge"><span>Edge</span></a></li>
<li class=""><a href="edgeuse.html" data-title="EdgeUse"><span>EdgeUse</span></a></li>
<li class=""><a href="face.html" data-title="Face"><span>Face</span></a></li>
<li class=""><a href="group.html" data-title="Group"><span>Group</span></a></li>
<li class=""><a href="image.html" data-title="Image"><span>Image</span></a></li>
<li class=""><a href="material.html" data-title="Material"><span>Material</span></a></li>
<li class=""><a href="layer.html" data-title="Layer"><span>Layer</span></a></li>
<li class=""><a href="loop.html" data-title="Loop"><span>Loop</span></a></li>
<li class=""><a href="page.html" data-title="Page"><span>Page</span></a></li>
<li class=""><a href="sectionplane.html" data-title="SectionPlane"><span>SectionPlane</span></a></li>
<li class=""><a href="shadowinfo.html" data-title="ShadowInfo"><span>ShadowInfo</span></a></li>
<li class=""><a href="style.html" data-title="Style"><span>Style</span></a></li>
<li class=""><a href="text.html" data-title="Text"><span>Text</span></a></li>
<li class=""><a href="texture.html" data-title="Texture"><span>Texture</span></a></li>
</ul></li>
<li class=""><a class="tlw-control tlw-collapsed">&nbsp;</a><span class="tlw-title tlw-control-title" data-title="Collection Classes">Collection Classes</span><ul ><li class=""><a href="attributedictionaries.html" data-title="AttributeDictionaries"><span>AttributeDictionaries</span></a></li>
<li class=""><a href="classifications.html" data-title="Classifications"><span>Classifications</span></a></li>
<li class=""><a href="definitionlist.html" data-title="DefinitionList"><span>DefinitionList</span></a></li>
<li class=""><a href="entities.html" data-title="Entities"><span>Entities</span></a></li>
<li class=""><a href="layers.html" data-title="Layers"><span>Layers</span></a></li>
<li class=""><a href="materials.html" data-title="Materials"><span>Materials</span></a></li>
<li class=""><a href="pages.html" data-title="Pages"><span>Pages</span></a></li>
<li class=""><a href="renderingoptions.html" data-title="RenderingOptions"><span>RenderingOptions</span></a></li>
<li class=""><a href="selection.html" data-title="Selection"><span>Selection</span></a></li>
<li class=""><a href="styles.html" data-title="Styles"><span>Styles</span></a></li>
<li class=""><a href="tools.html" data-title="Tools"><span>Tools</span></a></li>
</ul></li>
<li class=""><a class="tlw-control tlw-expanded">&nbsp;</a><span class="tlw-title tlw-control-title" data-title="Geom Classes">Geom Classes</span><ul style=""><li class=""><a href="geom.html" data-title="Geom"><span>Geom</span></a></li>
<li class=""><a href="boundingbox.html" data-title="Bounding Box"><span>Bounding Box</span></a></li>
<li class=""><a href="latlong.html" data-title="LatLong"><span>LatLong</span></a></li>
<li class=""><a href="point3d.html" data-title="Point3d"><span>Point3d</span></a></li>
<li class=""><a href="polygonmesh.html" data-title="PolygonMesh"><span>PolygonMesh</span></a></li>
<li class="active"><a href="vector3d.html" data-title="Vector3d"><span>Vector3d</span></a></li>
<li class=""><a href="vertex.html" data-title="Vertex"><span>Vertex</span></a></li>
<li class=""><a href="transformation.html" data-title="Transformation"><span>Transformation</span></a></li>
<li class=""><a href="utm.html" data-title="UTM"><span>UTM</span></a></li>
</ul></li>
<li class=""><a class="tlw-control tlw-collapsed">&nbsp;</a><span class="tlw-title tlw-control-title" data-title="UI Classes">UI Classes</span><ul ><li class=""><a href="ui.html" data-title="UI"><span>UI</span></a></li>
<li class=""><a href="command.html" data-title="Command"><span>Command</span></a></li>
<li class=""><a href="console.html" data-title="Console"><span>Console</span></a></li>
<li class=""><a href="inputpoint.html" data-title="InputPoint"><span>InputPoint</span></a></li>
<li class=""><a href="pickhelper.html" data-title="PickHelper"><span>PickHelper</span></a></li>
<li class=""><a href="menu.html" data-title="Menu"><span>Menu</span></a></li>
<li class=""><a href="tool.html" data-title="Tool"><span>Tool</span></a></li>
<li class=""><a href="toolbar.html" data-title="Toolbar"><span>Toolbar</span></a></li>
<li class=""><a href="webdialog.html" data-title="WebDialog"><span>WebDialog</span></a></li>
</ul></li>
<li class=""><a class="tlw-control tlw-collapsed">&nbsp;</a><span class="tlw-title tlw-control-title" data-title="Observer Classes">Observer Classes</span><ul ><li class=""><a href="appobserver.html" data-title="AppObserver"><span>AppObserver</span></a></li>
<li class=""><a href="definitionobserver.html" data-title="DefinitionObserver"><span>DefinitionObserver</span></a></li>
<li class=""><a href="definitionsobserver.html" data-title="DefinitionsObserver"><span>DefinitionsObserver</span></a></li>
<li class=""><a href="dimensionobserver.html" data-title="DimensionObserver"><span>DimensionObserver</span></a></li>
<li class=""><a href="entitiesobserver.html" data-title="EntitiesObserver"><span>EntitiesObserver</span></a></li>
<li class=""><a href="entityobserver.html" data-title="EntityObserver"><span>EntityObserver</span></a></li>
<li class=""><a href="instanceobserver.html" data-title="InstanceObserver"><span>InstanceObserver</span></a></li>
<li class=""><a href="layersobserver.html" data-title="LayersObserver"><span>LayersObserver</span></a></li>
<li class=""><a href="materialsobserver.html" data-title="MaterialsObserver"><span>MaterialsObserver</span></a></li>
<li class=""><a href="modelobserver.html" data-title="ModelObserver"><span>ModelObserver</span></a></li>
<li class=""><a href="optionsproviderobserver.html" data-title="OptionsProviderObserver"><span>OptionsProviderObserver</span></a></li>
<li class=""><a href="pagesobserver.html" data-title="PagesObserver"><span>PagesObserver</span></a></li>
<li class=""><a href="renderingoptionsobserver.html" data-title="RenderingOptionsObserver"><span>RenderingOptionsObserver</span></a></li>
<li class=""><a href="selectionobserver.html" data-title="SelectionObserver"><span>SelectionObserver</span></a></li>
<li class=""><a href="shadowinfoobserver.html" data-title="ShadowInfoObserver"><span>ShadowInfoObserver</span></a></li>
<li class=""><a href="toolsobserver.html" data-title="ToolsObserver"><span>ToolsObserver</span></a></li>
<li class=""><a href="viewobserver.html" data-title="ViewObserver"><span>ViewObserver</span></a></li>
</ul></li>
<li class=""><a class="tlw-control tlw-collapsed">&nbsp;</a><span class="tlw-title tlw-control-title" data-title="Core Ruby Classes">Core Ruby Classes</span><ul ><li class=""><a href="array.html" data-title="Array"><span>Array</span></a></li>
<li class=""><a href="length.html" data-title="Length"><span>Length</span></a></li>
<li class=""><a href="numeric.html" data-title="Numeric"><span>Numeric</span></a></li>
<li class=""><a href="string.html" data-title="String"><span>String</span></a></li>
</ul></li>
</ul></li>
<li class=""><a href="../releases.html" data-title="Release Notes"><span>Release Notes</span></a></li>
<li class=""><a href="../tos.html" data-title="Terms of Service"><span>Terms of Service</span></a></li>
</ul></nav>



      </div>
      

      <div id="gc-content">
        
        <div>

        
    <h1>Entities</h1>

<strong class="version">SketchUp 6.0+</strong>
  <h3 class="object_title">class</h3>
  <div class="parent_class"><b>Parent:&nbsp;</b>Object</div>
<ul class="heading_list">
  <li><a href="#introduction"><b>Introduction</b></a></li>
  <li><a href="#methods"><b>Methods</b></a></li>
  <li>
    <table class="method_list">
      <tr>
        <td class="method_list_empty_cell"/>
        <td class="method_list_cell"><a href="#[]">[]</a></td>
        <td class="method_list_cell"><a href="#add_face">add_face</a></td>
        <td class="method_list_cell"><a href="#count">count</a></td>
      </tr>
      <tr>
        <td class="method_list_empty_cell"/>
        <td class="method_list_cell"><a href="#active_section_plane">active_section_plane</a></td>
        <td class="method_list_cell"><a href="#add_faces_from_mesh">add_faces_from_mesh</a></td>
        <td class="method_list_cell"><a href="#each">each</a></td>
      </tr>
      <tr>
        <td class="method_list_empty_cell"/>
        <td class="method_list_cell"><a href="#active_section_plane=">active_section_plane=</a></td>
        <td class="method_list_cell"><a href="#add_group">add_group</a></td>
        <td class="method_list_cell"><a href="#erase_entities">erase_entities</a></td>
      </tr>
      <tr>
        <td class="method_list_empty_cell"/>
        <td class="method_list_cell"><a href="#add_3d_text">add_3d_text</a></td>
        <td class="method_list_cell"><a href="#add_image">add_image</a></td>
        <td class="method_list_cell"><a href="#fill_from_mesh">fill_from_mesh</a></td>
      </tr>
      <tr>
        <td class="method_list_empty_cell"/>
        <td class="method_list_cell"><a href="#add_arc">add_arc</a></td>
        <td class="method_list_cell"><a href="#add_instance">add_instance</a></td>
        <td class="method_list_cell"><a href="#intersect_with">intersect_with</a></td>
      </tr>
      <tr>
        <td class="method_list_empty_cell"/>
        <td class="method_list_cell"><a href="#add_circle">add_circle</a></td>
        <td class="method_list_cell"><a href="#add_line">add_line</a></td>
        <td class="method_list_cell"><a href="#length">length</a></td>
      </tr>
      <tr>
        <td class="method_list_empty_cell"/>
        <td class="method_list_cell"><a href="#add_cline">add_cline</a></td>
        <td class="method_list_cell"><a href="#add_ngon">add_ngon</a></td>
        <td class="method_list_cell"><a href="#model">model</a></td>
      </tr>
      <tr>
        <td class="method_list_empty_cell"/>
        <td class="method_list_cell"><a href="#add_cpoint">add_cpoint</a></td>
        <td class="method_list_cell"><a href="#add_observer">add_observer</a></td>
        <td class="method_list_cell"><a href="#parent">parent</a></td>
      </tr>
      <tr>
        <td class="method_list_empty_cell"/>
        <td class="method_list_cell"><a href="#add_curve">add_curve</a></td>
        <td class="method_list_cell"><a href="#add_section_plane">add_section_plane</a></td>
        <td class="method_list_cell"><a href="#remove_observer">remove_observer</a></td>
      </tr>
      <tr>
        <td class="method_list_empty_cell"/>
        <td class="method_list_cell"><a href="#add_dimension_linear">add_dimension_linear</a></td>
        <td class="method_list_cell"><a href="#add_text">add_text</a></td>
        <td class="method_list_cell"><a href="#size">size</a></td>
      </tr>
      <tr>
        <td class="method_list_empty_cell"/>
        <td class="method_list_cell"><a href="#add_dimension_radial">add_dimension_radial</a></td>
        <td class="method_list_cell"><a href="#at">at</a></td>
        <td class="method_list_cell"><a href="#transform_by_vectors">transform_by_vectors</a></td>
      </tr>
      <tr>
        <td class="method_list_empty_cell"/>
        <td class="method_list_cell"><a href="#add_edges">add_edges</a></td>
        <td class="method_list_cell"><a href="#clear!">clear!</a></td>
        <td class="method_list_cell"><a href="#transform_entities">transform_entities</a></td>
      </tr>
    </table>
  </li>
</ul>
<div class="clear"></div>
<h2 id="introduction">Introduction</h2>
<div class="introduction">
<p>
 The Entities class is a container class for all entities in a model (it is a
 collection of <a href="entity.html">Entity</a> objects).</p>
</div><h2 id="methods">Methods</h2>
<dl class="apireference"> <dt id="[]"><span class="itemname">Entities.[]</span><span class="version">SketchUp 6.0+</span></dt>
<dd>
<p>
 The [] method is used to retrieve an entity by its index in an array of
 entities. The index is a number between 0 and entities.count - 1. In
 general, it is preferable to use the "each" method to iterate though all
 of the entities in the collection as it will be much more efficient.</p>
<p class="subhead">Arguments:</p>
<dl class="param"><dt class="argname">index</dt>
<dd>The index for a specific entity.</dd></dl>
<p class="subhead">Returns:</p>
<dl class="return"><dt>entity</dt>
<dd>an <a href="entity.html">Entity</a> object if successful, nil if not
                      found</dd></dl>
<pre class="prettyprint">
 entities = Sketchup.active_model.entities
 entity0 = entities[0]
 if (entity0)
   UI.messagebox entity0
 else
   UI.messagebox "Failure"
 end</pre><br class="clear"/>
</dd></dl>
<div class="line"></div><dl class="apireference"> <dt id="active_section_plane"><span class="itemname">Entities.active_section_plane</span><span class="version">SketchUp 2014+</span></dt>
<dd>
<p>
 The active_section_plane method is used to access the currently active
 section plane in the Entities object.</p>
<p class="subhead">Returns:</p>
<dl class="return"><dt></dt>
<dd>              the active <a href="sectionplane.html">SectionPlane</a> or nil if none is active.</dd></dl>
<pre class="prettyprint">
 sp = Sketchup.active_model.entities.active_section_plane
 puts "Active section plane is #{sp}" if !sp.nil?</pre><br class="clear"/>
</dd></dl>
<div class="line"></div><dl class="apireference"> <dt id="active_section_plane="><span class="itemname">Entities.active_section_plane=</span><span class="version">SketchUp 2014+</span></dt>
<dd>
<p>
 The active_section_plane= method is used to set the active section plane in
 the Entities object.</p>
<p class="subhead">Arguments:</p>
<dl class="param"><dt class="argname">sec_plane</dt>
<dd>the <a href="sectionplane.html">SectionPlane</a> object to be set active. Pass nil to deactivate any active section plane.</dd></dl>
<p class="subhead">Returns:</p>
<dl class="return"><dt></dt>
<dd>              the <a href="sectionplane.html">SectionPlane</a> object that was set active.</dd></dl>
<pre class="prettyprint">
 entities = Sketchup.active_model.entities
 sp = entities.add_section_plane([50, 50, 0], [1.0, 1.0, 0])
 entities.active_section_plane = sp</pre><br class="clear"/>
</dd></dl>
<div class="line"></div><dl class="apireference"> <dt id="add_3d_text"><span class="itemname">Entities.add_3d_text</span><span class="version">SketchUp 6.0+</span></dt>
<dd>
<p>
 The add_3d_text is used to create 3D text. It will be added as edges and
 faces drawn at the origin.</p>
<p class="subhead">Arguments:</p>
<dl class="param"><dt class="argname">string</dt>
<dd>The text to create.</dd></dl>
<dl class="param"><dt class="argname">alignment</dt>
<dd>Number that defines the alignment. There are constants called TextAlignLeft, TextAlignRight, and TextAlignCenter that can be passed.</dd></dl>
<dl class="param"><dt class="argname">font</dt>
<dd><a href="string.html">String</a> font name.</dd></dl>
<dl class="param"><dt class="argname">is_bold</dt>
<dd>(optional) Boolean, true for bold.</dd></dl>
<dl class="param"><dt class="argname">is_italic</dt>
<dd>(optional) Boolean, true for italic.</dd></dl>
<dl class="param"><dt class="argname">letter_height</dt>
<dd>(optional) Height of the text in inches.</dd></dl>
<dl class="param"><dt class="argname">tolerance</dt>
<dd>(optional) Tolerance of the curve creation. Defaults to 0.0, which creates the highest possible curve quality.</dd></dl>
<dl class="param"><dt class="argname">z</dt>
<dd>(optional) z position in inches.</dd></dl>
<dl class="param"><dt class="argname">is_filled</dt>
<dd>(optional) Boolean, true for filled, which will put a face between the edges of the letters.</dd></dl>
<dl class="param"><dt class="argname">extrusion</dt>
<dd>(optional) Extrusion depth in inches. Defaults to 0.0.</dd></dl>
<p class="subhead">Returns:</p>
<dl class="return"><dt></dt>
<dd>              true if successful</dd></dl>
<pre class="prettyprint">
 # Draw the word "test" at the origin of the model, aligned left, in
 # Arial Bold, not italics, 1" in size, best tolerance quality, filled,
 # with an extrusion size of 5".
 entities = Sketchup.active_model.entities
 success = entities.add_3d_text('test', TextAlignLeft, "Arial",
   true, false, 1.0, 0.0, 0.5, true, 5.0)</pre><br class="clear"/>
</dd></dl>
<div class="line"></div><dl class="apireference"> <dt id="add_arc"><span class="itemname">Entities.add_arc</span><span class="version">SketchUp 6.0+</span></dt>
<dd>
<p>
 The add_arc method is used to create an arc curve segment.</p>
<p class="subhead">Arguments:</p>
<dl class="param"><dt class="argname">center</dt>
<dd>A <a href="point3d.html">Point3d</a> object representing the center .</dd></dl>
<dl class="param"><dt class="argname">xaxis</dt>
<dd>A <a href="vector3d.html">Vector3d</a> object representing xaxis for the arc.</dd></dl>
<dl class="param"><dt class="argname">normal</dt>
<dd>A <a href="vector3d.html">Vector3d</a> object representing normal for the arc.</dd></dl>
<dl class="param"><dt class="argname">radius</dt>
<dd>The radius of the arc.</dd></dl>
<dl class="param"><dt class="argname">start_angle</dt>
<dd>Start angle for the arc, in radians.</dd></dl>
<dl class="param"><dt class="argname">end_angle</dt>
<dd>End angle for the arc, in radians.</dd></dl>
<dl class="param"><dt class="argname">num_segments</dt>
<dd>(optional) How many segments to draw.</dd></dl>
<p class="subhead">Returns:</p>
<dl class="return"><dt>edges</dt>
<dd>an array of <a href="edge.html">Edge</a> objects that define the arc.</dd></dl>
<pre class="prettyprint">
 centerpoint = Geom::Point3d.new
 # Create a circle perpendicular to the normal or Z axis
 vector = Geom::Vector3d.new 0,0,1
 vector2 = Geom::Vector3d.new 1,0,0
 vector3 = vector.normalize!
 model = Sketchup.active_model
 entities = model.active_entities
 edges = entities.add_arc centerpoint, vector2, vector3, 10, 15.degrees, 135.degrees
 arccurve = edges.first.curve</pre><br class="clear"/>
</dd></dl>
<div class="line"></div><dl class="apireference"> <dt id="add_circle"><span class="itemname">Entities.add_circle</span><span class="version">SketchUp 6.0+</span></dt>
<dd>
<p>
 The add_circle method is used to create a circle.</p>
<p class="subhead">Arguments:</p>
<dl class="param"><dt class="argname">center</dt>
<dd>A <a href="point3d.html">Point3d</a> object representing the center .</dd></dl>
<dl class="param"><dt class="argname">normal</dt>
<dd>A <a href="vector3d.html">Vector3d</a> object representing normal for the arc.</dd></dl>
<dl class="param"><dt class="argname">radius</dt>
<dd>The radius of the arc.</dd></dl>
<dl class="param"><dt class="argname">numsegs</dt>
<dd>(optional) number of segments. Defaults to 24.</dd></dl>
<p class="subhead">Returns:</p>
<dl class="return"><dt>circle</dt>
<dd>an <a href="array.html">Array</a> object containing edges if successful</dd></dl>
<pre class="prettyprint">
 centerpoint = Geom::Point3d.new
 # Create a circle perpendicular to the normal or Z axis
 vector = Geom::Vector3d.new 0,0,1
 vector2 = vector.normalize!
 model = Sketchup.active_model
 entities = model.active_entities
 edges = entities.add_circle centerpoint, vector2, 10</pre><br class="clear"/>
</dd></dl>
<div class="line"></div><dl class="apireference"> <dt id="add_cline"><span class="itemname">Entities.add_cline</span><span class="version">SketchUp 6.0+</span></dt>
<dd>
<p>
 The add_cline method is used to create a construction line.</p>
<p class="subhead">Arguments:</p>
<dl class="param"><dt class="argname">start_point</dt>
<dd>A <a href="point3d.html">Point3d</a> object where the line will start.</dd></dl>
<dl class="param"><dt class="argname">end</dt>
<dd>If a <a href="vector3d.html">Vector3d</a>, then an infinite line passing through the start_point will be created in that direction. If a <a href="point3d.html">Point3d</a>, then a finite line will be created between the two points.</dd></dl>
<dl class="param"><dt class="argname">stipple</dt>
<dd>(optional) Stipple pattern. See <a href="constructionline.html">ConstructionLine</a>.stipple for acceptable patterns.</dd></dl>
<p class="subhead">Returns:</p>
<dl class="return"><dt>construction_line</dt>
<dd>a <a href="constructionline.html">ConstructionLine</a> object if
                      successful</dd></dl>
<pre class="prettyprint">
 model = Sketchup.active_model
 entities = model.active_entities
 point1 = Geom::Point3d.new(0,0,0)
 point2 = Geom::Point3d.new(20,20,20)
 constline = entities.add_cline point1,point2
 if (constline)
   UI.messagebox constline
 else
   UI.messagebox "Failure"
 end</pre><br class="clear"/>
</dd></dl>
<div class="line"></div><dl class="apireference"> <dt id="add_cpoint"><span class="itemname">Entities.add_cpoint</span><span class="version">SketchUp 6.0+</span></dt>
<dd>
<p>
 The add_cpoint method is used to create a construction point.</p>
<p class="subhead">Arguments:</p>
<dl class="param"><dt class="argname">point</dt>
<dd>A <a href="point3d.html">Point3d</a> object.</dd></dl>
<p class="subhead">Returns:</p>
<dl class="return"><dt>construction_point</dt>
<dd>a <a href="constructionpoint.html">ConstructionPoint</a> object if
                      successful</dd></dl>
<pre class="prettyprint">
 model = Sketchup.active_model
 entities = model.active_entities
 point1 = Geom::Point3d.new(100,200,300)
 constpoint = entities.add_cpoint point1
 if (constpoint)
   UI.messagebox constpoint
 else
   UI.messagebox "Failure"
 end</pre><br class="clear"/>
</dd></dl>
<div class="line"></div><dl class="apireference"> <dt id="add_curve"><span class="itemname">Entities.add_curve</span><span class="version">SketchUp 6.0+</span></dt>
<dd>
<p>
 The add_curve method is used to create a curve from a collection of edges.

<br/><br/> The arguments are either Points or an <a href="array.html">Array</a> of Points. At least 2 points are
 required.</p>
<p class="subhead">Arguments:</p>
<dl class="param"><dt class="argname">pts_or_array</dt>
<dd>You can pass either a series of <a href="point3d.html">Point3d</a> objects or a single array containing <a href="point3d.html">Point3d</a> objects.</dd></dl>
<p class="subhead">Returns:</p>
<dl class="return"><dt>curve</dt>
<dd>an array of Edges that make up the curve if
                      successful</dd></dl>
<pre class="prettyprint">
 entities = Sketchup.active_model.entities
 curve = entities.add_curve [0,0,0], [0,10,0], [1,20,0]</pre><br class="clear"/>
</dd></dl>
<div class="line"></div><dl class="apireference"> <dt id="add_dimension_linear"><span class="itemname">Entities.add_dimension_linear</span><span class="version">SketchUp 2014+</span></dt>
<dd>
<p>
 The add_dimension_linear method adds a linear dimension to the entities.</p>
<p class="subhead">Arguments:</p>
<dl class="param"><dt class="argname">start_pt_or_entity</dt>
<dd>the reference point and/or entity at the start of
                           the dimension. This parameter can take several
                           forms:
<ul>
<li>an <a href="inputpoint.html">InputPoint</a></li>
<li>a <a href="point3d.html">Point3d</a></li>
<li>a <a href="vertex.html">Vertex</a></li>
<li>a <a href="constructionpoint.html">ConstructionPoint</a></li>
<li>an array of size 2: [<a href="edge.html">Edge</a>, <a href="point3d.html">Point3d</a> along the edge].</li>
</ul>
                      Alternatively, these can be passed in as separate
                      parameters, turning this parameter into 2 parameters.
<ul>
<li>an array of size 2: [<a href="constructionline.html">ConstructionLine</a>, <a href="point3d.html">Point3d</a> along</li>
</ul>
                      the line] Alternatively, these can be passed in as
                      separate parameters, turning this parameter into 2
                      parameters.</dd></dl>
<dl class="param"><dt class="argname">end_pt_or_entity</dt>
<dd>the reference point and/or entity at the end of the dimension. This parameter takes the exact same forms as 'start_pt_or_entity'.</dd></dl>
<dl class="param"><dt class="argname">offset_vector</dt>
<dd>the parallel offset vector from the reference line to the dimension line measured from the 'start' reference point.</dd></dl>
<p class="subhead">Returns:</p>
<dl class="return"><dt>Entity</dt>
<dd>the created dimension</dd></dl>
<pre class="prettyprint">
 entities = Sketchup.active_model.entities
 # From point to point
 dim = entities.add_dimension_linear [50, 10, 0], [100, 10, 0], [0, 20, 0]
 # Between edge vertices
 edge = entities.add_edges([50,50,0], [40,10,0])[0]
 v0 = edge.start
 v1 = edge.end
 dim = entities.add_dimension_linear v0, v1, [0, 0, 20]
 # From an edge's midpoint to a construction point
 p0 = edge.start.position
 p1 = edge.end.position
 mp = Geom::Point3d.new((p0.x+p1.x)/2.0, (p0.y+p1.y)/2.0, (p0.z+p1.z)/2.0)
 cp = entities.add_cpoint [50, 10, 0]
 dim = entities.add_dimension_linear [edge, mp], cp, [20, 0, 0]
 # alternatively, the start params could be passed in separately
 dim = entities.add_dimension_linear edge, mp, cp, [20, 0, 0]</pre><br class="clear"/>
</dd></dl>
<div class="line"></div><dl class="apireference"> <dt id="add_dimension_radial"><span class="itemname">Entities.add_dimension_radial</span><span class="version">SketchUp 2014+</span></dt>
<dd>
<p>
 The add_dimension_radial method adds a radial dimension (i.e arc/circle
 radius/diameter dimension) to the entities.</p>
<p class="subhead">Arguments:</p>
<dl class="param"><dt class="argname">arc_curve</dt>
<dd>an <a href="arccurve.html">ArcCurve</a> object to which the dimension is to be attached.</dd></dl>
<dl class="param"><dt class="argname">leader_break_pt</dt>
<dd>a <a href="point3d.html">Point3d</a> for the break point on the leader where the dimension text is attached.</dd></dl>
<p class="subhead">Returns:</p>
<dl class="return"><dt></dt>
<dd>              the created dimension</dd></dl>
<pre class="prettyprint">
 entities = Sketchup.active_model.entities
 # Create a circle
 centerpoint = Geom::Point3d.new(10, 10, 0)
 vector = Geom::Vector3d.new(0, 0, 1)
 edges = entities.add_circle centerpoint, vector, 10
 circle = edges[0].curve
 dim = entities.add_dimension_radial circle, [30, 30, 0]</pre><br class="clear"/>
</dd></dl>
<div class="line"></div><dl class="apireference"> <dt id="add_edges"><span class="itemname">Entities.add_edges</span><span class="version">SketchUp 6.0+</span></dt>
<dd>
<p>
 The add_edges method is used to add a set of connected edges to the entities
 array.</p>
<p class="subhead">Arguments:</p>
<dl class="param"><dt class="argname">pts_or_array</dt>
<dd>You can pass either a series of <a href="point3d.html">Point3d</a> objects or a single array containing <a href="point3d.html">Point3d</a> objects.</dd></dl>
<p class="subhead">Returns:</p>
<dl class="return"><dt>edges</dt>
<dd>an array of <a href="edge.html">Edge</a> objects if successful</dd></dl>
<pre class="prettyprint">
 model = Sketchup.active_model
 entities = model.active_entities
 point1 = Geom::Point3d.new(0,0,0)
 point2 = Geom::Point3d.new(20,20,20)
 edges = entities.add_edges point1, point2</pre><br class="clear"/>
</dd></dl>
<div class="line"></div><dl class="apireference"> <dt id="add_face"><span class="itemname">Entities.add_face</span><span class="version">SketchUp 6.0+</span></dt>
<dd>
<p>
 The add_face method is used to create a face. You can call this method a
 number of ways:

<br/><br/><ul>
<li>entities.add_face(edge1, edge2, edge3, ...)</li>
<li>entities.add_face(edgearray)</li>
<li>entities.add_face(pt1, pt2, pt3, ...)</li>
<li>entities.add_face([pt1, pt2, pt3,...])</li>
<li>entities.add_face(curve)</li>
</ul>

<br/><br/> For the last form that takes a <a href="curve.html">Curve</a>, the curve must be closed - like a
 circle.

<br/><br/> Note that a special case exists for any face created on the ground plane, in
 which case the vertex order is ignored and the face is always facing down.</p>
<p class="subhead">Arguments:</p>
<dl class="param"><dt class="argname">some_entities</dt>
<dd>Either a series of <a href="edge.html">Edge</a> or <a href="point3d.html">Point3d</a> objects, an array of <a href="point3d.html">Point3d</a> objects, or a closed <a href="curve.html">Curve</a>.</dd></dl>
<p class="subhead">Returns:</p>
<dl class="return"><dt>face</dt>
<dd>a <a href="face.html">Face</a> object if successful</dd></dl>
<pre class="prettyprint">
 depth = 100
 width = 100
 model = Sketchup.active_model
 entities = model.active_entities
 pts = []
 pts[0] = [0, 0, 0]
 pts[1] = [width, 0, 0]
 pts[2] = [width, depth, 0]
 pts[3] = [0, depth, 0]
 # Add the face to the entities in the model
 face = entities.add_face pts
 if (face)
   UI.messagebox face
 else
   UI.messagebox "Failure"
 end</pre><br class="clear"/>
</dd></dl>
<div class="line"></div><dl class="apireference"> <dt id="add_faces_from_mesh"><span class="itemname">Entities.add_faces_from_mesh</span><span class="version">SketchUp 6.0+</span></dt>
<dd>
<p>
 The add_faces_from_mesh method is used to add <a href="face.html">Face</a> objects to the collection
 of entities from a <a href="polygonmesh.html">PolygonMesh</a>.

<br/><br/> The 2nd through 4th parameters are optional. The smooth_flags parameter
 can contain any of the following values if passed. The constants were added
 in SketchUp 2014. For previous versions, numeric values have to be specified
 instead of the Ruby constants.

<br/><br/><ul>
<li>0: Geom::PolygonMesh::NO_SMOOTH_OR_HIDE</li>
<li>1: Geom::PolygonMesh::HIDE_BASED_ON_INDEX (Negative point index will hide the edge.)</li>
<li>2: Geom::PolygonMesh::SOFTEN_BASED_ON_INDEX (Negative point index will soften the edge.)</li>
<li>4: Geom::PolygonMesh::AUTO_SOFTEN (Interior edges are softened.)</li>
<li>8: Geom::PolygonMesh::SMOOTH_SOFT_EDGES (All soft edges will also be smooth.)</li>
</ul>

<br/><br/> The 3rd and 4th parameters will accept a <a href="material.html">Material</a> object or a string name
 of a material currently in the model.</p>
<p class="subhead">Arguments:</p>
<dl class="param"><dt class="argname">polygonmesh</dt>
<dd>A Polygon mesh object.</dd></dl>
<dl class="param"><dt class="argname">smooth_flags</dt>
<dd>(optional) An integer containing flags for soften and smooth settings. Defaults to AUTO_SOFTEN | SMOOTH_SOFT_EDGES. See above.</dd></dl>
<dl class="param"><dt class="argname">f_material</dt>
<dd>(optional) <a href="material.html">Material</a> object to paint front faces with.</dd></dl>
<dl class="param"><dt class="argname">b_material</dt>
<dd>(optional) <a href="material.html">Material</a> object to paint back faces with.</dd></dl>
<p class="subhead">Returns:</p>
<dl class="return"><dt>faces</dt>
<dd>an array of <a href="face.html">Face</a> objects if successful</dd></dl>
<pre class="prettyprint">
 pm = Geom::PolygonMesh.new
 pm.add_point([ 0, 0, 0]) # 1
 pm.add_point([10, 0, 0]) # 2
 pm.add_point([10,10, 0]) # 3
 pm.add_point([ 0,10, 0]) # 4
 pm.add_point([20, 0, 5]) # 5
 pm.add_point([20,10, 5]) # 6
 pm.add_polygon(1,-2,3,4)
 pm.add_polygon(2,5,6,-3)

 # Create a new group that we will populate with the mesh.
 group = Sketchup.active_model.entities.add_group
 material = Sketchup.active_model.materials.add('green')
 smooth_flags = Geom::PolygonMesh::NO_SMOOTH_OR_HIDE
 group.entities.add_faces_from_mesh(pm, smooth_flags, material)</pre><br class="clear"/>
</dd></dl>
<div class="line"></div><dl class="apireference"> <dt id="add_group"><span class="itemname">Entities.add_group</span><span class="version">SketchUp 6.0+</span></dt>
<dd>
<p>
 The add_group method is used to create an empty group or a group with
 entities.

<br/><br/> NOTE: calling add_group with entities in its parameters has been known to
 crash SketchUp before version 8.0. It is preferable to create an empty
 group and then add things to its Entities collection.</p>
<p class="subhead">Arguments:</p>
<dl class="param"><dt class="argname">(optional)</dt>
<dd>an entities collection to add to the group.</dd></dl>
<p class="subhead">Returns:</p>
<dl class="return"><dt>group</dt>
<dd>the new group</dd></dl>
<pre class="prettyprint">
 model = Sketchup.active_model
 entities = model.active_entities
 group = entities.add_group
 if (group)
   UI.messagebox group
 else
   UI.messagebox "Failure"
 end</pre><br class="clear"/>
</dd></dl>
<div class="line"></div><dl class="apireference"> <dt id="add_image"><span class="itemname">Entities.add_image</span><span class="version">SketchUp 6.0+</span></dt>
<dd>
<p>
 The add_image method is used to add an image to the collection of entities.

<br/><br/> The width and height are measured in model units (i.e. inches). If the
 height is not given, then it is computed from the width to preserve the
 aspect ratio of the image.</p>
<p class="subhead">Arguments:</p>
<dl class="param"><dt class="argname">filename</dt>
<dd>A filename for the image file.</dd></dl>
<dl class="param"><dt class="argname">point</dt>
<dd>A <a href="point3d.html">Point3d</a> object representing the insertion point of the image.</dd></dl>
<dl class="param"><dt class="argname">width</dt>
<dd>Width for the image.</dd></dl>
<dl class="param"><dt class="argname">height</dt>
<dd>(optional) height for the image if you want to control width and height independently.</dd></dl>
<p class="subhead">Returns:</p>
<dl class="return"><dt>image</dt>
<dd>an <a href="image.html">Image</a> object if successful.</dd></dl>
<pre class="prettyprint">
 model = Sketchup.active_model
 entities = model.active_entities
 point = Geom::Point3d.new 10,20,30
 image = entities.add_image "Shapes.jpg", point, 300
 if (image)
   UI.messagebox image
 else
   UI.messagebox "Failure"
 end</pre><br class="clear"/>
</dd></dl>
<div class="line"></div><dl class="apireference"> <dt id="add_instance"><span class="itemname">Entities.add_instance</span><span class="version">SketchUp 6.0+</span></dt>
<dd>
<p>
 The add_instance method adds a component instance to the collection of
 entities.</p>
<p class="subhead">Arguments:</p>
<dl class="param"><dt class="argname">definition</dt>
<dd>A <a href="componentdefinition.html">ComponentDefinition</a> object.</dd></dl>
<dl class="param"><dt class="argname">transform</dt>
<dd>A <a href="transformation.html">Transformation</a> object.</dd></dl>
<p class="subhead">Returns:</p>
<dl class="return"><dt>componentinstance</dt>
<dd>a <a href="componentinstance.html">ComponentInstance</a> object if
                      successful</dd></dl>
<pre class="prettyprint">
 point = Geom::Point3d.new 10,20,30
 transform = Geom::Transformation.new point
 model = Sketchup.active_model
 entities = model.active_entities
 path = Sketchup.find_support_file "Bed.skp",
   "Components/Components Sampler/"
 definitions = model.definitions
 componentdefinition = definitions.load path
 instance = entities.add_instance componentdefinition, transform
 if (instance)
   UI.messagebox instance
 else
   UI.messagebox "Failure"
 end</pre><br class="clear"/>
</dd></dl>
<div class="line"></div><dl class="apireference"> <dt id="add_line"><span class="itemname">Entities.add_line</span><span class="version">SketchUp 6.0+</span></dt>
<dd>
<p>
 The add_line method is used to add an edge to the collection of entities.
 This is not to be confused with the concept of a "line" from a geometric
 sense, which is an invisible object represented by an <a href="array.html">Array</a> of a point
 and a vector. (See the <a href="array.html">Array</a> class for more information on geometric lines in
 SketchUp.)

<br/><br/> This method is the same as add_edges method, but returns a single edge.</p>
<p class="subhead">Arguments:</p>
<dl class="param"><dt class="argname">point1</dt>
<dd><a href="point3d.html">Point3d</a> object representing the edge's starting point.</dd></dl>
<dl class="param"><dt class="argname">point2</dt>
<dd><a href="point3d.html">Point3d</a> object representing the edge's ending point.</dd></dl>
<p class="subhead">Returns:</p>
<dl class="return"><dt>edge</dt>
<dd>a <a href="edge.html">Edge</a> object if successful</dd></dl>
<pre class="prettyprint">
 model = Sketchup.active_model
 entities = model.active_entities
 point1 = Geom::Point3d.new(0,0,0)
 point2 = Geom::Point3d.new(20,20,20)
 line = entities.add_line point1,point2
 if (line)
   UI.messagebox line
 else
   UI.messagebox "Failure"
 end</pre><br class="clear"/>
</dd></dl>
<div class="line"></div><dl class="apireference"> <dt id="add_ngon"><span class="itemname">Entities.add_ngon</span><span class="version">SketchUp 6.0+</span></dt>
<dd>
<p>
 The add_ngon method is used to create a multi-sided polygon.</p>
<p class="subhead">Arguments:</p>
<dl class="param"><dt class="argname">center</dt>
<dd>A <a href="point3d.html">Point3d</a> object representing the center of the polygon.</dd></dl>
<dl class="param"><dt class="argname">normal</dt>
<dd>A <a href="vector3d.html">Vector3d</a> object.</dd></dl>
<dl class="param"><dt class="argname">radius</dt>
<dd>A radius.</dd></dl>
<dl class="param"><dt class="argname">numsides</dt>
<dd>The number of sides for the polygon.</dd></dl>
<p class="subhead">Returns:</p>
<dl class="return"><dt>edges</dt>
<dd>an array of Edges that make up the polygon if
                      successful</dd></dl>
<pre class="prettyprint">
 entities = Sketchup.active_model.entities
 center = Geom::Point3d.new
 normal = Geom::Vector3d.new(0,0,1)
 radius = 100
 numsides = 6
 edges = entities.add_ngon center, normal, radius, numsides</pre><br class="clear"/>
</dd></dl>
<div class="line"></div><dl class="apireference"> <dt id="add_observer"><span class="itemname">Entities.add_observer</span><span class="version">SketchUp 6.0+</span></dt>
<dd>
<p>
 The add_observer method is used to add an observer to the current object.</p>
<p class="subhead">Arguments:</p>
<dl class="param"><dt class="argname">observer</dt>
<dd>An observer.</dd></dl>
<p class="subhead">Returns:</p>
<dl class="return"><dt></dt>
<dd>              true if successful, false if unsuccessful.</dd></dl>
<pre class="prettyprint">
 entities = Sketchup.active_model.entities
 status = entities.add_observer observer</pre><br class="clear"/>
</dd></dl>
<div class="line"></div><dl class="apireference"> <dt id="add_section_plane"><span class="itemname">Entities.add_section_plane</span><span class="version">SketchUp 2014+</span></dt>
<dd>
<p>
 The add_section_plane method adds a section plane object to the entities.</p>
<p class="subhead">Arguments:</p>
<dl class="param"><dt class="argname">plane</dt>
<dd>the geometric plane where the <a href="sectionplane.html">SectionPlane</a> object is to be created. Refer to the <a href="geom.html">Geom</a> module for information on how planes are represented.</dd></dl>
<p class="subhead">Returns:</p>
<dl class="return"><dt></dt>
<dd>              the created <a href="sectionplane.html">SectionPlane</a> object if successful, nil on
                      failure.</dd></dl>
<pre class="prettyprint">
 # Create a section plane
 model = Sketchup.active_model
 sp = model.entities.add_section_plane([50, 50, 0], [1.0, 1.0, 0])
 # Activate it
 sp.activate
 # Make sure section planes are visible
 model.rendering_options['DisplaySectionPlanes'] = true</pre><br class="clear"/>
</dd></dl>
<div class="line"></div><dl class="apireference"> <dt id="add_text"><span class="itemname">Entities.add_text</span><span class="version">SketchUp 6.0+</span></dt>
<dd>
<p>
 The add_text method adds a note or label text entity to the entities</p>
<p class="subhead">Arguments:</p>
<dl class="param"><dt class="argname">text</dt>
<dd>The text string to add.</dd></dl>
<dl class="param"><dt class="argname">point</dt>
<dd>A <a href="point3d.html">Point3d</a> object representing the insertion point.</dd></dl>
<dl class="param"><dt class="argname">vector</dt>
<dd>(optional) vector representing an arrow leader.</dd></dl>
<p class="subhead">Returns:</p>
<dl class="return"><dt>text</dt>
<dd>a <a href="text.html">Text</a> object if successful</dd></dl>
<pre class="prettyprint">
 coordinates = [10, 10, 10]
 model = Sketchup.active_model
 entities = model.entities
 point = Geom::Point3d.new coordinates
 text = entities.add_text "This is a Test", point</pre><br class="clear"/>
</dd></dl>
<div class="line"></div><dl class="apireference"> <dt id="at"><span class="itemname">Entities.at</span><span class="version">SketchUp 6.0+</span></dt>
<dd>
<p>
 The at method is an alias for []. See [].</p>
<p class="subhead">Returns:</p>
<dl class="return"><dt>              nil</dt>
<dd></dd></dl>
<pre class="prettyprint">
 entities = Sketchup.active_model.entities
 entity0 = entities.at(0)
 if (entity0)
   UI.messagebox entity0
 else
   UI.messagebox "Failure"
 end</pre><br class="clear"/>
</dd></dl>
<div class="line"></div><dl class="apireference"> <dt id="clear!"><span class="itemname">Entities.clear!</span><span class="version">SketchUp 6.0+</span></dt>
<dd>
<p>
 The clear! method is used to remove all entities from the collection of
 entities.</p>
<p class="subhead">Returns:</p>
<dl class="return"><dt>status</dt>
<dd>true if successful, false if unsuccessful</dd></dl>
<pre class="prettyprint">
 coordinates = [10, 10, 10]
 model = Sketchup.active_model
 entities = model.entities
 point = Geom::Point3d.new coordinates
 text = entities.add_text "This is a Test", point
 UI.messagebox "Clearing All"
 status = entities.clear!</pre><br class="clear"/>
</dd></dl>
<div class="line"></div><dl class="apireference"> <dt id="count"><span class="itemname">Entities.count</span><span class="version">SketchUp 6.0+</span></dt>
<dd>
<p>
 Since SketchUp 2014 the count method is inherited from Ruby's Enumable mix-in
 module. Prior to that the count method is an alias for length.</p>
<p class="subhead">Returns:</p>
<dl class="return"><dt></dt>
<dd>              integer</dd></dl>
<pre class="prettyprint">
 model = Sketchup.active_model
 entities = model.entities
 entities.add_cpoint([10, 10, 10])
 number = entities.count</pre><br class="clear"/>
</dd></dl>
<div class="line"></div><dl class="apireference"> <dt id="each"><span class="itemname">Entities.each</span><span class="version">SketchUp 6.0+</span></dt>
<dd>
<p>
 The each method is used to iterate through the entities in the collection of
 entities.</p>
<p class="subhead">Arguments:</p>
<dl class="param"><dt class="argname">entity</dt>
<dd>A variable that will hold each <a href="entity.html">Entity</a> object as they are found if successful.</dd></dl>
<p class="subhead">Returns:</p>
<dl class="return"><dt>              nil</dt>
<dd></dd></dl>
<pre class="prettyprint">
 coordinates = [10, 10, 10]
 model = Sketchup.active_model
 entities = model.entities
 point = Geom::Point3d.new coordinates
 text = entities.add_text "This is a Test", point
 entities.each { | entity| UI.messagebox entity }</pre><br class="clear"/>
</dd></dl>
<div class="line"></div><dl class="apireference"> <dt id="erase_entities"><span class="itemname">Entities.erase_entities</span><span class="version">SketchUp 6.0+</span></dt>
<dd>
<p>
 The erase_entities method is used to erase one or more entities from the
 model.</p>
<p class="subhead">Arguments:</p>
<dl class="param"><dt class="argname">entities</dt>
<dd>An entity or array of entities.</dd></dl>
<p class="subhead">Returns:</p>
<dl class="return"><dt>              nil</dt>
<dd></dd></dl>
<pre class="prettyprint">
 depth = 100
 width = 100
 model = Sketchup.active_model
 entities = model.active_entities
 pts = []
 pts[0] = [0, 0, 0]
 pts[1] = [width, 0, 0]
 pts[2] = [width, depth, 0]
 pts[3] = [0, depth, 0]

 # Add the face to the entities in the model
 face = entities.add_face pts

 # I just happen to know that the second entity in the
 # entities objects is an edge, so erase it.
 UI.messagebox entities
 entities.erase_entities entities[1]
 UI.messagebox entities</pre><br class="clear"/>
</dd></dl>
<div class="line"></div><dl class="apireference"> <dt id="fill_from_mesh"><span class="itemname">Entities.fill_from_mesh</span><span class="version">SketchUp 6.0+</span></dt>
<dd>
<p>
 The fill_from_mesh method is used to add faces and edges to the collection of
 entities from a <a href="polygonmesh.html">PolygonMesh</a>. It requires that the entities collection to be
 filled is empty. It has higher performance than add_faces_from_mesh, but
 does less error checking as it builds the geometry.

<br/><br/> The 2nd through 5th parameters are optional. The smooth_flags parameter
 can contain any of the following values if passed. The constants were added
 in SketchUp 2014. For previous versions, numeric values have to be specified
 instead of the Ruby constants.

<br/><br/><ul>
<li>0: Geom::PolygonMesh::NO_SMOOTH_OR_HIDE</li>
<li>1: Geom::PolygonMesh::HIDE_BASED_ON_INDEX (Negative point index will hide the edge.)</li>
<li>2: Geom::PolygonMesh::SOFTEN_BASED_ON_INDEX (Negative point index will soften the edge.)</li>
<li>4: Geom::PolygonMesh::AUTO_SOFTEN (Interior edges are softened.)</li>
<li>8: Geom::PolygonMesh::SMOOTH_SOFT_EDGES (All soft edges will also be smooth.)</li>
</ul>

<br/><br/> The 4rd and 5th parameters will accept a <a href="material.html">Material</a> object or a string name
 of a material currently in the model.</p>
<p class="subhead">Arguments:</p>
<dl class="param"><dt class="argname">polygonmesh</dt>
<dd>A Polygon mesh object.</dd></dl>
<dl class="param"><dt class="argname">weld_vertices</dt>
<dd>(optional) Boolean. This argument has no effect and is kept for compatibility reasons. Points are always merged.</dd></dl>
<dl class="param"><dt class="argname">smooth_flags</dt>
<dd>(optional) An integer containing flags for soften and smooth settings. Defaults to AUTO_SOFTEN | SMOOTH_SOFT_EDGES. See above.</dd></dl>
<dl class="param"><dt class="argname">f_material</dt>
<dd>(optional) <a href="material.html">Material</a> object to paint front faces with.</dd></dl>
<dl class="param"><dt class="argname">b_material</dt>
<dd>(optional) <a href="material.html">Material</a> object to paint back faces with.</dd></dl>
<p class="subhead">Returns:</p>
<dl class="return"><dt>status</dt>
<dd>true if successful</dd></dl>
<pre class="prettyprint">
 pm = Geom::PolygonMesh.new
 pm.add_point([ 0, 0, 0]) # 1
 pm.add_point([10, 0, 0]) # 2
 pm.add_point([10,10, 0]) # 3
 pm.add_point([ 0,10, 0]) # 4
 pm.add_point([20, 0, 5]) # 5
 pm.add_point([20,10, 5]) # 6
 pm.add_polygon(1,-2,3,4)
 pm.add_polygon(2,5,6,-3)

 # Create a new group that we will populate with the mesh.
 group = Sketchup.active_model.entities.add_group
 material = Sketchup.active_model.materials.add('red')
 smooth_flags = Geom::PolygonMesh::HIDE_BASED_ON_INDEX
 group.entities.fill_from_mesh(pm, true, smooth_flags, material)</pre><br class="clear"/>
</dd></dl>
<div class="line"></div><dl class="apireference"> <dt id="intersect_with"><span class="itemname">Entities.intersect_with</span><span class="version">SketchUp 6.0+</span></dt>
<dd>
<p>
 The intersect_with method is used to intersect an entities, component
 instance, or group object with a entities object.</p>
<p class="subhead">Arguments:</p>
<dl class="param"><dt class="argname">recurse</dt>
<dd>true if you want this entities object to be recursed (intersection lines will be put inside of groups and components within this entities object).</dd></dl>
<dl class="param"><dt class="argname">transform1</dt>
<dd>The transformation for this entities object.</dd></dl>
<dl class="param"><dt class="argname">entities1</dt>
<dd>The entities object where you want the intersection lines to appear.</dd></dl>
<dl class="param"><dt class="argname">transform2</dt>
<dd>The transformation for entities1.</dd></dl>
<dl class="param"><dt class="argname">hidden</dt>
<dd>true if you want hidden geometry in this entities object to be used in the intersection.</dd></dl>
<dl class="param"><dt class="argname">entities2</dt>
<dd>A single entity, or an array of entities.</dd></dl>
<p class="subhead">Returns:</p>
<dl class="return"><dt>              nil</dt>
<dd></dd></dl>
<pre class="prettyprint">
 entities.intersect_with recurse, transformation1, entities1,
   transformation2, hidden, entities2</pre><br class="clear"/>
</dd></dl>
<div class="line"></div><dl class="apireference"> <dt id="length"><span class="itemname">Entities.length</span><span class="version">SketchUp 6.0+</span></dt>
<dd>
<p>
 The length method is used to retrieve the number of entities in the
 collection of entities.</p>
<p class="subhead">Returns:</p>
<dl class="return"><dt>integer</dt>
<dd>the number of entities in the collection of
                      entities if successful</dd></dl>
<pre class="prettyprint">
 model = Sketchup.active_model
 entities = model.entities
 entities.add_cpoint([10, 10, 10])
 number = entities.length</pre><br class="clear"/>
</dd></dl>
<div class="line"></div><dl class="apireference"> <dt id="model"><span class="itemname">Entities.model</span><span class="version">SketchUp 6.0+</span></dt>
<dd>
<p>
 The model method is used to retrieve the model that contains the collection
 of entities.</p>
<p class="subhead">Returns:</p>
<dl class="return"><dt>model</dt>
<dd>the model that contains the collection of
                      entities if successful.</dd></dl>
<pre class="prettyprint">
 coordinates = [10, 10, 10]
 model = Sketchup.active_model
 entities = model.entities
 point = Geom::Point3d.new coordinates
 text = entities.add_text "This is a Test", point
 model = entities.model</pre><br class="clear"/>
</dd></dl>
<div class="line"></div><dl class="apireference"> <dt id="parent"><span class="itemname">Entities.parent</span><span class="version">SketchUp 6.0+</span></dt>
<dd>
<p>
 The parent method is used to retrieve the parent or object that contains the
 collection of entities. A parent can be either a <a href="model.html">Model</a> or
 <a href="componentdefinition.html">ComponentDefinition</a> object.</p>
<p class="subhead">Returns:</p>
<dl class="return"><dt>parent</dt>
<dd>the object that contains the collection of
                      entities if successful</dd></dl>
<pre class="prettyprint">
 coordinates = [10, 10, 10]
 model = Sketchup.active_model
 entities = model.entities
 point = Geom::Point3d.new coordinates
 text = entities.add_text "This is a Test", point
 parent = entities.parent</pre><br class="clear"/>
</dd></dl>
<div class="line"></div><dl class="apireference"> <dt id="remove_observer"><span class="itemname">Entities.remove_observer</span><span class="version">SketchUp 6.0+</span></dt>
<dd>
<p>
 The remove_observer method is used to remove an observer from the current
 object.</p>
<p class="subhead">Arguments:</p>
<dl class="param"><dt class="argname">observer</dt>
<dd>An observer.</dd></dl>
<p class="subhead">Returns:</p>
<dl class="return"><dt></dt>
<dd>              true if successful, false if unsuccessful.</dd></dl>
<pre class="prettyprint">
 entities = Sketchup.active_model.entities
 status = entities.remove_observer observer</pre><br class="clear"/>
</dd></dl>
<div class="line"></div><dl class="apireference"> <dt id="size"><span class="itemname">Entities.size</span><span class="version">SketchUp 2014+</span></dt>
<dd>
<p>
 The size method is an alias for the length method. See length.</p>
<p class="subhead">Returns:</p>
<dl class="return"><dt></dt>
<dd>              integer</dd></dl>
<pre class="prettyprint">
 model = Sketchup.active_model
 entities = model.entities
 entities.add_cpoint([10, 10, 10])
 number = entities.size</pre><br class="clear"/>
</dd></dl>
<div class="line"></div><dl class="apireference"> <dt id="transform_by_vectors"><span class="itemname">Entities.transform_by_vectors</span><span class="version">SketchUp 6.0+</span></dt>
<dd>
<p>
 The transform_by_vectors method is used to apply several vectors to several
 sub-entities all at once.</p>
<p class="subhead">Arguments:</p>
<dl class="param"><dt class="argname">sub_entities</dt>
<dd>An array of entities to transform.</dd></dl>
<dl class="param"><dt class="argname">vectors</dt>
<dd>An array of vectors to apply.</dd></dl>
<p class="subhead">Returns:</p>
<dl class="return"><dt>              nil</dt>
<dd></dd></dl>
<pre class="prettyprint">
 # Need better Ruby example.
 entities = entities.transform_by_vectors sub_entities, vector_array</pre><br class="clear"/>
</dd></dl>
<div class="line"></div><dl class="apireference"> <dt id="transform_entities"><span class="itemname">Entities.transform_entities</span><span class="version">SketchUp 6.0+</span></dt>
<dd>
<p>
 The transform_entities method is used to apply a transform to several
 sub-entities all at once.

<br/><br/> Important note: If you apply a transformation to entities that are
 not in the current edit context (i.e. faces that are inside a group),
 SketchUp will apply the transformation incorrectly, since the geometry
 has one origin and the current edit context has another. You can correct
 for this by watching the <a href="model.html">Model</a>.edit_transform and <a href="model.html">Model</a>.active_path. See
 <a href="modelobserver.html">ModelObserver</a>.onActivePathChanged for more information.</p>
<p class="subhead">Arguments:</p>
<dl class="param"><dt class="argname">transform</dt>
<dd>The <a href="transformation.html">Transformation</a> to apply.</dd></dl>
<dl class="param"><dt class="argname">entities</dt>
<dd>An array or series of entities to transform.</dd></dl>
<p class="subhead">Returns:</p>
<dl class="return"><dt>status</dt>
<dd>results of the transform.</dd></dl>
<pre class="prettyprint">
 entities = Sketchup.active_model.entities
 entities.add_line([0,0,0],[100,100,100])
 entities.add_line([0,0,0],[200,-10,-10])

 entities_to_transform = []
 entities_to_transform.push(entities[0])
 entities_to_transform.push(entities[1])

 transform = Geom::Transformation.new([100,0,0])
 entities.transform_entities(transform, ent1, ent2, ent3)</pre><br class="clear"/>
</dd></dl>
<p class="post">&nbsp;&nbsp;</p>
</div>

        </div>
        
<div id="gc-content-footer">





</div>




      </div>

      </div>
      

      
      
      <div id="about"><center><a href="http://www.trimble.com/"><img alt="Trimble Home" src="../../../../../images/FooterTrimble.png"></a><br /><a href="http://www.trimble.com/corporate/about_trimble.aspx">About Trimble</a> - <a href="http://www.trimble.com/privacy.aspx">Privacy Policy</a> - <a href="http://support.google.com/sketchup/bin/request.py?customer=supro&amp;contact_type=sales">Contact Us</a></center></div>
      
      
    </div>
    
    <script src="../../assets/script_foot.js"></script>
    <script>
      (function($) {
        devsite.devsite.Init($, null, '');
      })(jQuery);

      
      devsite.localInit = function() {
        document.getElementById('quick-reference-nav').style.display = 'block';
      };
      
    </script>

    



<script type="text/javascript">
$(document).ready(function(e) {
    // Render any carousels on the page
    $('.carousel').carousel();
    // Render any feed widgets on the page
    
    $('.feed').rss();
    $('.feed-plain').rss();
    // Render any OSS widgets on the page.
    $('.oss').oss();
    });
</script>

<script type="text/javascript" defer="">


$(document).ready(function() {
    contentTimer.name = 'content';
    contentTimer.tick('ol');
    window.jstiming.report(contentTimer);

    // Boilerplate javascript to enable the plusone button
    var po = document.createElement('script'); po.type = 'text/javascript';
    po.async = true;
    po.src = '../../../../../../apis.google.com/js/plusone4608.js?onload=devsite_plusoneLoaded';
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(po, s);
});
</script>




  

<script type="text/javascript">window.NREUM||(NREUM={});NREUM.info={"beacon":"bam.nr-data.net","licenseKey":"d7657f89f1","applicationID":"1894794","transactionName":"YlYBZkFRVkoCUxUPXlscNkBaH1FXF1xOA18aVwZEVlxXSQZCTgJeVkBMXUZCXFYAHwQIRVxHCldAHkhREw==","queueTime":0,"applicationTime":4,"atts":"ThECEAlLRUQ=","errorBeacon":"bam.nr-data.net","agent":""}</script></body>
<!-- Mirrored from www.sketchup.com/intl/en/developer/docs/ourdoc/entities by HTTrack Website Copier/3.x [XR&CO'2014], Mon, 11 Apr 2016 13:59:36 GMT -->
</html>
